<?php
$this->title = "matricula";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'aluno',
        'action'=>'add'));?>">Adicionar novo aluno</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'disciplina',
        'action'=>'add'));?>">Adicionar nova disciplina</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'matricula',
        'action'=>'add'));?>">Adicionar Matricula</a></p>
<table>
    <tr>
        <th>Nome</th>
        <th>Disciplinas</th>
        <th></th>
    </tr>
    <?php
    $lastAluno = null;
    foreach($this->matricula as $matricula) :
    if ($matricula['aluno'] != $lastAluno) {
    $lastAluno = $matricula['aluno'];
    ?>
    <tr>
        <td><?php echo $this->escape($matricula['aluno']);?></td>
        <td><?php echo $this->escape($matricula['disciplina']);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'matricula',
                'action'=>'delete', 'id'=>$matricula['id']));?>">Excluir</a>
        </td>
    </tr>
    <?php } else { ?>
    <tr>
        <td></td>
        <td><?php echo $this->escape($matricula['disciplina']);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'matricula',
                'action'=>'delete', 'id'=>$matricula['id']));?>">Excluir</a>
        </td>
    </tr>
    <?php }; ?>
    <?php endforeach; ?>
</table>